name: Analyzer release

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    container: cruizba/ubuntu-dind:focal-25.0.3
    permissions:
      contents: write
      packages: write

    steps:
      - name: Setup Git
        run: apt update && apt install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y.%m.%d').$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build analyzer jar
        run: ./gradlew :projectAnalyzerJar -PanalyzerVersion=${{ steps.version.outputs.version }}
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Build analyzer docker amd64 image
        run: ./gradlew :buildProjectAnalyzerDocker -PanalyzerVersion=${{ steps.version.outputs.version }} -PdockerPlatform=linux/amd64
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Build analyzer docker arm64 image
        run: ./gradlew :buildProjectAnalyzerDocker -PanalyzerVersion=${{ steps.version.outputs.version }} -PdockerPlatform=linux/arm64
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Create image names
        run: |
          echo "ANALYZER_IMAGE_AMD=ghcr.io/${{ github.repository_owner }}/seqra-jvm-sast/sast-analyzer-amd64:${{ steps.version.outputs.version }}" >> $GITHUB_ENV
          echo "ANALYZER_IMAGE_ARM=ghcr.io/${{ github.repository_owner }}/seqra-jvm-sast/sast-analyzer-arm64:${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Tag images
        run: |
          docker tag analyzer-private-linux-amd64:${{ steps.version.outputs.version }} ${{ env.ANALYZER_IMAGE_AMD }}
          docker tag analyzer-private-linux-arm64:${{ steps.version.outputs.version }} ${{ env.ANALYZER_IMAGE_ARM }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          docker push ${{ env.ANALYZER_IMAGE_AMD }}
          docker push ${{ env.ANALYZER_IMAGE_ARM }}

      - name: Upload analyzer jar
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          prerelease: true
          files: build/libs/seqra-project-analyzer.jar
          make_latests: false
